#' Classify bathymetry data into depth zones
#'
#' @description This function takes a bathymetric raster (depths must be negative and in meters) and reclassifies depths to categorical depth zones. If geospatial data are not in the appropriate coordinate reference system, users can specify a planning grid to reproject the bathymetry data. 
#' 
#' @details The depth groups are categorized as follows: 
#' \itemize{
#' \item Epipelagic Zone: 0-200 m depth
#' \item Mesopelagic Zone: 200-1000 m depth
#' \item Bathypelagic Zone: 1000-4000 m depth
#' \item Abyssopelagic Zone: 4000-6000 m depth
#' \item Hadopelagic Zone: 6000+ m depth
#' }
#' 
#' @param bathymetry_raster a raster of bathymetry data (meters) that you wish to categorize; depths must be negative
#' @param planning_grid a raster template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#'
#' @return A raster of depth zones, rasterized to the planning grid resolution and CRS if supplied.
#' @export 
#'
#' @examples 
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Grab bathymetry data
#' bathymetry <- get_bathymetry(area_polygon = bermuda_eez)
#' # Classify depths 
#' depth_zones <- classify_depths(bathymetry)
#' depth_zones
classify_depths <- function(bathymetry_raster, planning_grid = NULL){
  
  depth_zone_names <- c("epipelagic", "mesopelagic", "bathypelagic", "abyssopelagic", "hadopelagic")
  
  if(is.null(planning_grid)){
    depth_classification <- bathymetry_raster %>%
      raster::reclassify(c(-200, Inf, 1,
                   -1000, -200, 2,
                   -4000, -1000, 3,
                   -6000, -4000, 4,
                   -12000, -6000, 5))
      
    depth_zones_stack <- depth_classification %>% 
      raster::layerize() %>% 
      raster::reclassify(c(-0.1,0.1,NA)) %>% 
      setNames(depth_zone_names[raster::cellStats(depth_classification, min):raster::cellStats(depth_classification, max)])
  } else{
    depth_classification <- bathymetry_raster %>%
      raster::projectRaster(., to = planning_grid) %>% 
      raster::mask(planning_grid) %>% 
      raster::reclassify(c(-200, Inf, 1,
                           -1000, -200, 2,
                           -4000, -1000, 3,
                           -6000, -4000, 4,
                           -12000, -6000, 5))
    
    depth_zones_stack <- depth_classification %>% 
      raster::layerize() %>% 
      raster::mask(planning_grid) %>% 
      raster::reclassify(c(-0.1,0.1,NA)) %>% 
      setNames(depth_zone_names[raster::cellStats(depth_classification, min):raster::cellStats(depth_classification, max)])
  }
  return(depth_zones_stack)
}