#' Get geomorphology for an area of interest
#' 
#' @description This function gathers geomorpholgical deatures in the area of interest.
#' 
#' @details Geomorphological features are from the Harris et al. 2014 dataset, available at: https://www.bluehabitats.org
#'
#' @param area_polygon an sf polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param planning_grid a raster or sf template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#'
#' @return A raster stack with geomorphological features found within the area polygon rasterized using the planning_grid input raster, or a list of geomorphological features in sfc format
#' @export
#'
#' @examples
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Get geomorphology
#' geomorphology <- get_geomorphology(area_polygon = bermuda_eez)
get_geomorphology <- function(area_polygon = NULL, planning_grid = NULL, antimeridian = FALSE){
  
  check_grid_or_polygon(planning_grid, area_polygon)
  
  geomorph_files <- c("Basins_Basins perched on the shelf.rds", "Basins_Basins perched on the slope.rds", 
                      "Basins_Large basins of seas and oceans.rds", "Basins_Major ocean basins.rds", 
                      "Basins_Small basins of seas and oceans.rds", "Bridges.rds", 
                      "Canyons_blind.rds", "Canyons_shelf incising.rds", "Escarpments.rds", 
                      "Fans.rds", "Glacial_troughs.rds", "Guyots.rds", "Plateaus.rds", 
                      "Ridges.rds", "Rift_valleys.rds", "Rises.rds", "Shelf_valleys_Large shelf valleys and glacial troughs.rds", 
                      "Shelf_valleys_Moderate size shelf valley.rds", "Shelf_valleys_Small shelf valley.rds", 
                      "Sills.rds", "Spreading_ridges.rds", "Terraces.rds", "Trenches.rds", 
                      "Troughs.rds")
  
  geomorph_file_paths <- system.file("extdata", geomorph_files, package = "offshoredatr", mustWork = TRUE)

  sf::sf_use_s2(FALSE)

  geomorph_data <- list()
  
  meth <- if(check_raster(planning_grid)) 'near' else 'mode'

  for (i in 1:length(geomorph_file_paths)) {
    feature_name <- tolower(gsub(pattern =  ".rds", replacement =  "", 
                                 gsub(pattern = " ", replacement = "_", basename(geomorph_file_paths[i]))))
    
    geomorph_layer <- geomorph_file_paths[i] %>% 
      readRDS() %>% 
      dplyr::mutate(geomorph_type = feature_name, .before = 1)
    
    geomorph_data[[i]] <- data_to_planning_grid(area_polygon = area_polygon, planning_grid = planning_grid, dat = geomorph_layer, meth = meth, name = feature_name, antimeridian = antimeridian)
    
  }
  sf::sf_use_s2(TRUE)
 
  if(!is.null(area_polygon)){
    do.call(rbind, geomorph_data) %>% 
      sf::st_cast(to = "MULTIPOLYGON")
  } else if(check_raster(geomorph_data[[1]])){
    geomorph_ras <- terra::rast(geomorph_data)
    
    na_index <- is.na(terra::minmax(geomorph_ras)[1,])
    if(all(na_index == TRUE)){
      stop("No data present in the planning grid")
    }else geomorph_ras[[!na_index]]
  }else{ #sf planning grid case
    non_zero_index <- (sapply(geomorph_data, function(x) sum(x[[1]], na.rm = TRUE)) >0)
    if(all(non_zero_index == FALSE)){
      stop("No data present in the planning grid")
    }else{
      geomorph_data <- geomorph_data[non_zero_index] 
      
      lapply(geomorph_data[1:(length(geomorph_data)-1)], function(x) sf::st_drop_geometry(x)) %>% 
        do.call(cbind, .) %>% 
        cbind(geomorph_data[[length(geomorph_data)]]) %>% 
        sf::st_sf()
    }
  }
}