#' Get knolls base areas for area of interest
#'
#' @description This function identifies areas of knolls (small seamounts, seamounts with peaks 200-1000 m higher than the surrounding seafloor (Morato et al., 2008))
#' 
#' @details These data are the knoll base area data from Yesson et al. (2011)
#'
#' @param area_polygon an sf polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param planning_grid a raster or sf template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#'
#' @return A raster of knolls found within the area polygon, rasterized using the planning_grid input raster, or an sf object of knolls for the area of interest if no planning grid is supplied
#' @export
#'
#' @examples
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Get knolls
#' knolls <- get_knolls(area_polygon = bermuda_eez)
get_knolls <- function(area_polygon, planning_grid = NULL){
  
  # Add repeated errors for area_polygon and planning_grid (these are present for nearly all functions)
  check_grid(planning_grid)
  check_area(area_polygon)
  
  suppressMessages({
    suppressWarnings({
      knolls <- system.file("extdata", "knolls.rds", package = "offshoredatr", mustWork = TRUE) %>%
        readRDS() %>% 
        sf::st_geometry() %>% 
        sf::st_crop(area_polygon) %>%
        sf::st_intersection(area_polygon)
    }) 
  })
    
    if(is.null(planning_grid)){
      return(knolls)
     }
    else if (class(planning_grid)[1] %in% c("RasterLayer", "SpatRaster")) {
      knolls <- knolls %>%
        sf::st_transform(crs = sf::st_crs(planning_grid)) %>% 
        terra::vect() %>% 
        terra::rasterize(planning_grid, field = 1) %>% 
        setNames("knolls")
      
      return(knolls) 
    } else { 
      
      suppressWarnings({
        knolls <- knolls %>% 
          sf::st_transform(crs = sf::st_crs(planning_grid)) %>% 
          sf::st_as_sf() %>% 
          dplyr::mutate(knolls = 1)  %>%
          dplyr::select(knolls) %>% 
          sf::st_join(planning_grid, ., largest = TRUE) 
      })
      
      return(knolls)
  }
}