#' Get coral habitat suitability data for area of interest
#' 
#' @description This function extracts coral habitat suitability in the area of interest and re-defines areas as presence (1) or absence (0) for three groups of deep-water coral species (antipatharia, cold water corals, octocorals). See Details for more information on the species data available.
#' 
#' @details Habitat suitability data are available for the following species groups: 
#' \itemize{
#' \item Antipatharia: The global extent of black coral habiatat suitability modelled using Maxent. The antipatharia habitat suitability is converted to a presence/absence map "by choosing a threshold value of habitat suitability based on the maximum sum of sensitivity and specificity (threshold mss = 0.23)" (Yesson et al. 2017). This threshold can be altered via the function input. Data from Yesson et al. (2017).
#' \item Cold water corals: The global habitat suitability for five species of Scleractinia modelled using Maxent. Presence defined using Maxent values above the lowest 10 percent of values. Data from Davies and Guinotte (2011).
#' \item Octocorals: The global habitat suitability modelled for 7 species of cold-water octocoral found deeper than 50m. Data from and described in Yesson et al. (2012): "A consensus/summary map incorporating all seven octocoral suborders was constructed by generating binary presence/absence maps from the model outputs indicating areas of high suitability using a score threshold that maximized the sum of the specificity and sensitivity based on the validation data (Carroll, 2010). These binary layers were summed to generate a layer containing the number of octocoral suborders predicted to be present per cell."
#' }
#' 
#' @param area_polygon an sf polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param planning_grid a raster or sf template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#' @param octocoral_threshold numeric between 0 and 7; the threshold value for how many species (of 7) should be predicted present in an area for octocorals to be considered present (default is 2)
#' @param antipatharia_threshold numeric between 0 and 100; the threshold value for habitat suitability for antipatharia corals to be considered present (default is 22, as defined in Yesson et al., 2017)
#'
#' @return A raster stack with of coral habitat suitabilities within the area polygon, this is rasterized using the planning_grid input raster if supplied
#' @export
#'
#' @examples
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Get coral habitat
#' coral_habitat <- get_coral_habitat(area_polygon = bermuda_eez)
get_coral_habitat <- function(area_polygon, planning_grid = NULL, antipatharia_threshold = 22, octocoral_threshold = 2){
 
  # Add repeated errors for area_polygon and planning_grid (these are present for nearly all functions)
  check_area(area_polygon)
  check_grid(planning_grid)
  
  # Add errors if the thresholds are not within the right area
  if(antipatharia_threshold < 0 | antipatharia_threshold > 100) { 
    stop("antipatharia_threshold must be between 0 and 100, as it represents the percent threshold of habitat suitability antipatharia to be considered present")
  }
  if(octocoral_threshold < 1 | octocoral_threshold > 7) { 
    stop("octocoral_threshold must be between 1 and 7, as it represents the number of octocoral species (out of 7) must be present in an area for octocorals as a whole to be considered present")
  }
  
  # Data message 
  report_message <- function(coral_data) { 
    if (terra::global(eval(as.name(coral_data)), "sum", na.rm = TRUE) < 1) { 
      message(paste0("No ", gsub("_", " ", coral_data), "in area of interest. Processing output..."))
    } else {
      message(paste0("Data found for ", gsub("_", " ", coral_data), ". Processing output...")) 
    }
  }
  
  antipatharia <- system.file("extdata", "YessonEtAl_2016_Antipatharia.tif", package = "offshoredatr", mustWork = TRUE) %>% 
    terra::rast() %>% 
    terra::crop(area_polygon, mask = TRUE) %>% 
    setNames("antipatharia")
  
  cold_corals <- system.file("extdata", "binary_grid_figure7.tif", package = "offshoredatr", mustWork = TRUE) %>% 
    terra::rast() %>% 
    terra::crop(area_polygon, mask = TRUE) %>% 
    setNames("cold_corals")

  octocorals <- system.file("extdata", "YessonEtAl_Consensus.tif", package = "offshoredatr", mustWork = TRUE) %>% 
    terra::rast() %>% 
    terra::crop(area_polygon, mask = TRUE) %>% 
    setNames("octocoral")
  
  antipatharia_matrix <- matrix(c(0, antipatharia_threshold, NA,
                                  antipatharia_threshold, 100, 1), ncol = 3, byrow = TRUE)
  cold_corals_matrix <- matrix(c(0, 0.5, NA, 
                                 0.5, 1.1, 1), ncol = 3, byrow = TRUE)
  octocoral_matrix <- matrix(c(0, octocoral_threshold, NA,
                               octocoral_threshold,7, 1), ncol = 3, byrow = TRUE)
  
  if(round(sf::st_bbox(area_polygon)[1]) <= -180 & round(sf::st_bbox(area_polygon)[3]) >= 180) { 
    message("Data cross the antimeridian - completing this step in two parts") 
    # Antipatharia 
    report_message("antipatharia")
    antipatharia_halves <- split_by_antimeridian(antipatharia)
    message("Processing first half...")
    antipatharia_left_side <- classify_layers(antipatharia_halves[[1]], 
                                              planning_grid = planning_grid, 
                                              classification_matrix = antipatharia_matrix, 
                                              classification_names = "antipatharia")
    message("Processing second half...")
    antipatharia_right_side <- classify_layers(antipatharia_halves[[2]], 
                                               planning_grid = planning_grid, 
                                               classification_matrix = antipatharia_matrix, 
                                               classification_names = "antipatharia")
    antipatharia_stack <- combine_antimeridian(data = list(antipatharia_left_side, antipatharia_right_side), 
                                              planning_grid = planning_grid, 
                                              classification_names = "antipatharia")
    
    # Cold corals
    report_message("cold_corals")
    cold_corals_halves <- split_by_antimeridian(cold_corals)
    message("Processing first half...")
    cold_corals_left_side <- classify_layers(cold_corals_halves[[1]], 
                                             planning_grid = planning_grid,  
                                              classification_matrix = cold_corals_matrix, 
                                              classification_names = "cold_corals")
    message("Processing second half...")
    cold_corals_right_side <- classify_layers(cold_corals_halves[[2]], 
                                              planning_grid = planning_grid,  
                                               classification_matrix = cold_corals_matrix, 
                                               classification_names = "cold_corals")
    cold_corals_stack <- combine_antimeridian(data = list(cold_corals_left_side, cold_corals_right_side), 
                                               planning_grid = planning_grid, 
                                               classification_names = "cold_corals")
    
    # Octocoral
    report_message("octocorals")
    octocorals_halves <- split_by_antimeridian(octocorals)
    message("Processing first half...")
    octocorals_left_side <- classify_layers(octocorals_halves[[1]], 
                                              planning_grid = planning_grid, 
                                              classification_matrix = octocoral_matrix, 
                                              classification_names = "octocoral")
    message("Processing second half...")
    octocorals_right_side <- classify_layers(octocorals_halves[[2]], 
                                               planning_grid = planning_grid,  
                                               classification_matrix = octocoral_matrix, 
                                               classification_names = "octocoral")
    octocorals_stack <- combine_antimeridian(data = list(octocorals_left_side, octocorals_right_side), 
                                               planning_grid = planning_grid, 
                                               classification_names = "octocoral")
  } else {
    
    # Antipatharia
    report_message("antipatharia")
    antipatharia_stack <- classify_layers(data = antipatharia, 
                                         planning_grid = planning_grid, 
                                         classification_matrix = antipatharia_matrix, 
                                         classification_names = "antipatharia")
    
    # Cold corals
    report_message("cold_corals")
    cold_corals_stack <- classify_layers(data = cold_corals, 
                                         planning_grid = planning_grid, 
                                         classification_matrix = cold_corals_matrix, 
                                         classification_names = "cold_corals")
    
    # Octocoral
    report_message("octocorals")
    octocorals_stack <- classify_layers(data = octocorals, 
                                          planning_grid = planning_grid, 
                                          classification_matrix = octocoral_matrix, 
                                          classification_names = "octocoral")
    
  }
  
  if(class(planning_grid)[1] %in% c("RasterLayer", "SpatRaster") | is.null(planning_grid)) { 
    corals_stack <- c(antipatharia_stack, cold_corals_stack, octocorals_stack) %>% 
      terra::subset(which(terra::global(., "sum", na.rm = TRUE) >1))
  } else { 
    corals_stack <- antipatharia_stack %>% 
      cbind(cold_corals_stack %>% sf::st_drop_geometry()) %>% 
      cbind(octocorals_stack %>% sf::st_drop_geometry())
  }
  
  return(corals_stack)
  gc()
}