#' Get geomorphology for an area of interest
#' 
#' @description This function gathers geomorpholgical deatures in the area of interest.
#' 
#' @details Geomorphological features are from the Harris et al. 2014 dataset, available at: https://www.bluehabitats.org
#'
#' @param area_polygon an sf polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param planning_grid a raster or sf template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#'
#' @return A raster stack with geomorphological features found within the area polygon rasterized using the planning_grid input raster, or a list of geomorphological features in sfc format
#' @export
#'
#' @examples
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Get geomorphology
#' geomorphology <- get_geomorphology(area_polygon = bermuda_eez)
get_geomorphology <- function(area_polygon, planning_grid = NULL){
  
  # Add repeated errors for area_polygon and planning_grid (these are present for nearly all functions)
  if(!(class(area_polygon)[1] == "sf")) { 
    stop("area_polygon must be an sf object")}
  
  if(!is.null(planning_grid) & !(class(planning_grid)[1] %in% c("RasterLayer", "SpatRaster", "sf"))) { 
    stop("planning_grid must be a raster or sf object")}
  
  if(class(planning_grid)[1] == "sf") { 
    message("sf planning grids will take slightly longer to process")
    }
  
  geomorph_files <- c("Basins_Basins perched on the shelf.rds", "Basins_Basins perched on the slope.rds", 
                      "Basins_Large basins of seas and oceans.rds", "Basins_Major ocean basins.rds", 
                      "Basins_Small basins of seas and oceans.rds", "Bridges.rds", 
                      "Canyons_blind.rds", "Canyons_shelf incising.rds", "Escarpments.rds", 
                      "Fans.rds", "Glacial_troughs.rds", "Guyots.rds", "Plateaus.rds", 
                      "Ridges.rds", "Rift_valleys.rds", "Rises.rds", "Shelf_valleys_Large shelf valleys and glacial troughs.rds", 
                      "Shelf_valleys_Moderate size shelf valley.rds", "Shelf_valleys_Small shelf valley.rds", 
                      "Sills.rds", "Spreading_ridges.rds", "Terraces.rds", "Trenches.rds", 
                      "Troughs.rds")
  
  geomorph_file_paths <- system.file("extdata", geomorph_files, package = "offshoredatr", mustWork = TRUE)

  sf::sf_use_s2(FALSE)

  geomorph_data <- list()

  for (file_name in geomorph_file_paths) {
    feature_name <- tolower(gsub(pattern =  ".rds", replacement =  "", 
                                 gsub(pattern = " ", replacement = "_", basename(file_name))))
    
    suppressMessages({
    area_polygon_sfc <- area_polygon %>% 
      sf::st_union()
    
    temp_file <- readRDS(file_name) %>%
      sf::st_crop(area_polygon_sfc) %>%
      sf::st_intersection(area_polygon_sfc)
    })

    if(nrow(temp_file)>0)
    {
      geomorph_data[[feature_name]] <- temp_file
    }
  }

  if(is.null(planning_grid)){
    return(geomorph_data)
  }
  else if (class(planning_grid)[1] %in% c("RasterLayer", "SpatRaster")){
    
    for (geomorph_feature in names(geomorph_data)) {
    
      geomorph_data_stack <- geomorph_data[[geomorph_feature]] %>%
        sf::st_transform(crs = sf::st_crs(planning_grid)) %>%
        terra::vect() %>% 
        terra::rasterize(planning_grid, field = 1) %>%
        setNames(geomorph_feature) %>% 
        {if(geomorph_feature != names(geomorph_data)[1]) c(geomorph_data_stack, .)}
      
    }
    
    return(terra::rast(geomorph_data_stack))
  } else { 
    
    geomorph_data_stack <- NULL 
    
    for (geomorph_feature in names(geomorph_data)) {
      suppressWarnings({
        geomorph_data_stack_temp <- geomorph_data[[geomorph_feature]] %>% 
          sf::st_transform(crs = sf::st_crs(planning_grid)) %>% 
          sf::st_as_sf() %>% 
          dplyr::mutate(!!geomorph_feature := 1)  %>% 
          sf::st_join(planning_grid, ., largest = TRUE) 
      })
      
      if(geomorph_feature != names(geomorph_data)[1]){ 
        geomorph_data_stack <- geomorph_data_stack_temp %>% 
          sf::st_drop_geometry() %>% 
          cbind(geomorph_data_stack, .)
      } else { 
        geomorph_data_stack <- geomorph_data_stack_temp}
    } 
      return(geomorph_data_stack)
  }
}