#' Get knolls base areas for area of interest or planning grid
#'
#' @description This function gets knolls base area data within an area polygon or planning grid depending on which is supplied
#' 
#' @details Knolls are small seamounts; seamounts with peaks 200-1000 m higher than the surrounding seafloor [(Morato et al., 2008)](https://doi.org/10.3354/meps07268). The knolls base area data is from [Yesson et al. 2011](https://doi.org/10.1016/j.dsr.2011.02.004)
#'
#' @param area_polygon an `sf` polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param spatial_grid a `terra::rast()` or `sf` planning grid with the desired resolution and coordinate reference system generated by `get_grid()`. For a raster, values in the planning grid cells should be 1, while all other values are NA
#' @param name name of raster or column in sf object that is returned
#' @param antimeridian does `area_polygon` or `spatial_grid` span the antimeridian? If so, this should be set to `TRUE`, otherwise set to `FALSE`. If set to `NULL` (default) the function will try to check if data spans the antimeridian and set this appropriately.
#'
#' @return If an `area_polygon` is supplied, an `sf` object of knolls for that area. If a `spatial_grid` is supplied, a raster or `sf` of gridded knolls data, depending on `spatial_grid` format.
#' @export
#'
#' @examples
#' # Get EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda", mregions_column = "territory1")
#' # Get knolls
#' knolls <- get_knolls(area_polygon = bermuda_eez)
#' # Get knolls in a planning grid
#' planning_grid <- get_grid(area_polygon = bermuda_eez, projection_crs = '+proj=laea +lon_0=-64.8108333 +lat_0=32.3571917 +datum=WGS84 +units=m +no_defs', resolution = 5000)
#' knolls_gridded <- get_knolls(spatial_grid = planning_grid)
get_knolls <- function(area_polygon = NULL, spatial_grid = NULL, name = "knolls", antimeridian = NULL){
  
  check_grid_or_polygon(spatial_grid, area_polygon)
  
      knolls <- system.file("extdata", "knolls.rds", package = "oceandatr", mustWork = TRUE) %>%
        readRDS() 
      
      get_data_in_grid(area_polygon = area_polygon, spatial_grid = spatial_grid, dat = knolls, name = "knolls", antimeridian = antimeridian)
    
}
