#' Get ecoregions for area of interest or a spatial grid
#'
#' @description 
#' Gets ecoregion data within an area polygon or planning grid depending on which is supplied
#' 
#' @details
#' The Following ecoregions can be obtained:
#' * Marine Ecosystems of the World [dataset](https://www.worldwildlife.org/publications/marine-ecoregions-of-the-world-a-bioregionalization-of-coastal-and-shelf-areas)
#' * [Longhurst Provinces](https://www.sciencedirect.com/book/9780124555211/ecological-geography-of-the-sea?via=ihub=)
#' * [Large Marine Ecosystems of the World](http://geonode.iwlearn.org/layers/geonode:lmes)
#' 
#' All data are downloaded via the `mregions2` R package function `mregions2::mrp_get()`, and more information on the data can be found on the [Marine Regions website](https://marineregions.org/sources.php)
#' 
#' @param area_polygon an `sf` polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param spatial_grid a `terra::rast()` or `sf` grid with the desired resolution and coordinate reference system generated by `get_grid()`. For a raster, values in the grid cells should be 1 for the study area and NA for all other cells.
#' @param type which ecoregion type is required? Default is `MEOW` (Marine Ecosystems of the World); other possible values are `Longhurst` and `\"LME\"`
#' @param antimeridian does `area_polygon` or `spatial_grid` span the antimeridian? If so, this should be set to `TRUE`, otherwise set to `FALSE`. If set to `NULL` (default) the function will try to check if data spans the antimeridian and set this appropriately.
#'
#' @return  If an `area_polygon` is supplied, an `sf` object of the chosen ecoregions for that area. If a `spatial_grid` is supplied, a raster or `sf` of gridded ecoregions data, depending on `spatial_grid` format.
#' @export
#'
#' @examples 
#' #' # Get EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda", mregions_column = "territory1")
#' # Get Marine Ecoregions of the World data
#' ecoregions <- get_ecoregion(area_polygon = bermuda_eez)
#' # Get Longhurst Provinces in a planning grid
#' bermuda_grid <- get_grid(area_polygon = bermuda_eez, projection_crs = '+proj=laea +lon_0=-64.8108333 +lat_0=32.3571917 +datum=WGS84 +units=m +no_defs', resolution = 5000)
#' longhurst_gridded <- get_ecoregion(spatial_grid = bermuda_grid, type = "Longhurst")
get_ecoregion <- function(area_polygon = NULL, spatial_grid = NULL, type = "MEOW", antimeridian = NULL){
  
  check_grid_or_polygon(spatial_grid, area_polygon)
  
  if(type == "MEOW"){
    type <- "ecoregions"
    col_name <- "ecoregion"
  } else if(type == "Longhurst"){
    type <- "longhurst"
    col_name <- "provdescr"
  } else if(type == "LME"){
    type <- "lme"
    col_name <- "lme_name"
  }else message("type must be one of MEOW, Longhurst or LME.")
  
  marine_ecoregions <- mregions2::mrp_get(type)
  sf::sf_use_s2(FALSE)
 ecoregion_data <- get_data_in_grid(area_polygon = area_polygon, spatial_grid = spatial_grid, dat = marine_ecoregions, antimeridian = antimeridian, feature_names = col_name)
  sf::sf_use_s2(TRUE)
  return(ecoregion_data)
}