#' Get distance to shore for a spatial grid
#' 
#' @description
#' Calculates distance from shore for each grid cell in the provided spatial grid. Spatial grid can be `terra::rast()` or `sf` format. The Natural Earth high resolution land polygons are used as the coastline and are downloaded from the Natural Earth website (https://www.naturalearthdata.com/downloads/10m-physical-vectors/), so an internet connection is required.
#' 
#' @param spatial_grid a `terra::rast()` or `sf` planning grid with the desired resolution and coordinate reference system generated by `get_grid()`. For a raster, values in the planning grid cells should be 1, while all other values are NA
#'
#' @return a `terra::rast` or `sf` object (same type as `spatial_grid` input) with distance to shore for each grid cell.
#' @export
#'
#' @examples
#' # Get EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda", mregions_column = "territory1")
#' # Get a planning grid
#' planning_grid <- get_grid(area_polygon = bermuda_eez, projection_crs = '+proj=laea +lon_0=-64.8108333 +lat_0=32.3571917 +datum=WGS84 +units=m +no_defs', resolution = 5000)
#' dist_from_shore_rast <- get_dist_shore(planning_grid)
#' terra::plot(dist_from_shore_rast)
get_dist_shore <- function(spatial_grid){
  if(!any(check_raster(spatial_grid), check_sf(spatial_grid))) stop("spatialgrid must be in raster or sf format")
     
     #get high res land polygons from Natural Earth
     ne_data_filename <- "ne_land_data.zip"
     
     if(!file.exists(file.path(tempdir(), "ne_10m_land.shp"))){
       utils::download.file(url = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_land.zip", destfile = file.path(tempdir(), ne_data_filename), mode = "wb", quiet = TRUE)
       utils::unzip(file.path(tempdir(), ne_data_filename), exdir = tempdir())
     }
     
     ne_data <- sf::read_sf(file.path(tempdir(), "ne_10m_land.shp")) %>% 
       sf::st_geometry() %>% 
       sf::st_sf() 
     
     matching_crs <- if(sf::st_crs(spatial_grid) == sf::st_crs(4326)) TRUE else FALSE
     
     if(check_raster(spatial_grid)){
       
       if(matching_crs){
         spatial_grid %>% 
           terra::distance(terra::vect(ne_data)) %>% 
           terra::mask(spatial_grid)
       }else{
         dist_vect <- spatial_grid %>% 
           terra::as.data.frame(xy = TRUE, cell = TRUE) %>% 
           sf::st_as_sf(coords = c("x", "y"), crs = sf::st_crs(spatial_grid)) %>%
           sf::st_geometry() %>% 
           sf::st_sf() %>% 
           sf::st_transform(4326) %>% 
           sf::st_distance(ne_data) %>% 
           {do.call(pmin, as.data.frame(.))} 
         
         spatial_grid[!is.na(spatial_grid)] <- dist_vect
         return(spatial_grid)
       }
     } else{
       temp_grid <- spatial_grid %>% 
         {if(matching_crs) . else sf::st_transform(., 4326)}
       
       temp_grid %>% 
         sf::st_centroid() %>% 
         sf::st_distance(ne_data) %>% 
         {do.call(pmin, as.data.frame(.))} %>% 
         cbind(temp_grid) %>% 
         dplyr::rename(dist_shore = 1) %>% 
         {if(matching_crs) . else sf::st_transform(., sf::st_crs(spatial_grid))}
         
     }
     
}