#' Get bathymetry data for the area of interest
#'
#' @description This function extracts bathymetry data for the area of interest from the ETOPO 2022 Global Relief model. If data are already downloaded locally, the user can specify the file path of the dataset. See Details for more information.
#' 
#' @details If the user has downloaded data for the area of interest, for example from GEBCO (https://www.gebco.net), they can pass the file path to this function and it will crop and rasterize the data using the supplied planning grid. If no file path is provided, the function will extract bathymetry data for the area from the ETOPO 2022 Global Relief model served by NOAA (https://www.ncei.noaa.gov/products/etopo-global-relief-model).
#'
#' @param area_polygon an sf polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param planning_grid a raster template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#' @param bathymetry_data_filepath string; the file path (including file name and extension) where bathymetry raster data are saved locally
#' @param resolution numeric; the resolution (in decimal degrees) of data to pull from the ETOPO 2022 Global Relief model
#' @param keep logical; whether to save the bathymetry data locally
#' @param path string; the file path where you would like to save bathymetry data
#' @param download_timeout numeric; the maximum number of seconds a query is allowed to run
#'
#' @return A raster of bathymetry for the area of interest, rasterized to the planning grid resolution and CRS if supplied.
#' @export
#'
#' @examples
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Grab bathymetry data
#' bathymetry <- get_bathymetry(area_polygon = bermuda_eez)
get_bathymetry <- function(area_polygon, planning_grid = NULL, bathymetry_data_filepath = NULL, resolution = 1, keep = FALSE, path = NULL, download_timeout = 300){
  
  # Add repeated errors for area_polygon and planning_grid (these are present for nearly all functions)
  if(!(class(area_polygon)[1] == "sf")) { 
    stop("area_polygon must be an sf object")}
  
  if(!is.null(planning_grid) & !(class(planning_grid)[1] %in% c("RasterLayer", "SpatRaster", "sf"))) { 
    stop("planning_grid must be a raster or sf object")}
  
  if(is.null(bathymetry_data_filepath)){
    bathymetry <- get_etopo_bathymetry(area_polygon, resolution = resolution, keep = keep, path = path, download_timeout = download_timeout)
  }
  else{
    bathymetry <- terra::rast(bathymetry_data_filepath) %>% 
      terra::crop(area_polygon, mask=TRUE)
  }
  if(is.null(planning_grid)){
    return(bathymetry)
  }
  else{
    bathymetry_planning_grid <- bathymetry %>% 
      terra::project(planning_grid) %>%
      terra::mask(planning_grid) %>%
      setNames("bathymetry")
    return(bathymetry_planning_grid)
  }
}