#' Get coral habitat suitability data for area of interest
#' 
#' @description This function extracts coral habitat suitability in the area of interest and re-defines areas as presence (1) or absence (0) for three groups of deep-water coral species (antipatharia, cold water corals, octocorals). See Details for more information on the species data available.
#' 
#' @details Habitat suitability data are available for the following species groups: 
#' \itemize{
#' \item Antipatharia: The global extent of black coral habiatat suitability modelled using Maxent. The antipatharia habitat suitability is converted to a presence/absence map "by choosing a threshold value of habitat suitability based on the maximum sum of sensitivity and specificity (threshold mss = 0.23)" (Yesson et al. 2017). This threshold can be altered via the function input. Data from Yesson et al. (2017).
#' \item Cold water corals: The global habitat suitability for five species of Scleractinia modelled using Maxent. Presence defined using Maxent values above the lowest 10 percent of values. Data from Davies and Guinotte (2011).
#' \item Octocorals: The global habitat suitability modelled for 7 species of cold-water octocoral found deeper than 50m. Data from and described in Yesson et al. (2012): "A consensus/summary map incorporating all seven octocoral suborders was constructed by generating binary presence/absence maps from the model outputs indicating areas of high suitability using a score threshold that maximized the sum of the specificity and sensitivity based on the validation data (Carroll, 2010). These binary layers were summed to generate a layer containing the number of octocoral suborders predicted to be present per cell."
#' }
#' 
#' @param area_polygon an sf polygon or multipolygon object of the area of interest (e.g., a country's EEZ)
#' @param planning_grid a raster template with the desired resolution and coordinate reference system generated by `get_planning_grid()`; values in areas of interest are 1, while all other values are NA
#' @param octocoral_threshold numeric between 0 and 7; the threshold value for how many species (of 7) should be predicted present in an area for octocorals to be considered present (default is 2)
#' @param antipatharia_threshold numeric between 0 and 1; the threshold value for habitat suitability for antipatharia corals to be considered present (default is 0.23, as defined in Yesson et al., 2017)
#'
#' @return A raster stack with of coral habitat suitabilities within the area polygon, this is rasterized using the planning_grid input raster if supplied
#' @export
#'
#' @examples
#' # Grab EEZ data first 
#' bermuda_eez <- get_area(area_name = "Bermuda")
#' # Get coral habitat
#' coral_habitat <- get_coral_habitat(area_polygon = bermuda_eez)
get_coral_habitat <- function(area_polygon, planning_grid = NULL, antipatharia_threshold = 0.22, octocoral_threshold = 2){
 
  antipatharia <- system.file("extdata", "YessonEtAl_2016_Antipatharia.tif", package = "offshoredatr", mustWork = TRUE) %>% 
    terra::rast() %>% 
    terra::crop(area_polygon, mask = TRUE) %>% 
    setNames("Antipatharia")
  
  ifelse(terra::global(antipatharia, "sum") < 1, print("No antipatharia in area of interest"), print("Antipatharia data done"))

  
  cold_corals <- system.file("extdata", "binary_grid_figure7.tif", package = "offshoredatr", mustWork = TRUE) %>% 
    terra::rast() %>% 
    terra::crop(area_polygon, mask = TRUE) %>% 
    setNames("Cold_Corals")
  
  ifelse(terra::global(cold_corals, "sum") < 1, print("No octocorals in area of interest"), print("Cold water coral data done"))
  
  octocorals <- system.file("extdata", "YessonEtAl_Consensus.tif", package = "offshoredatr", mustWork = TRUE) %>% 
    terra::rast() %>% 
    terra::crop(area_polygon, mask = TRUE) %>% 
    setNames("Octocoral")
  
  ifelse(terra::global(octocorals, "sum") < 1, print("No octocorals in area of interest"), print("Octocoral data done"))
  
  corals_stack <- c(antipatharia, cold_corals, octocorals) %>% 
    terra::subset(which(terra::global(., "sum") >1))
  
  if(is.null(planning_grid)){
    return(corals_stack)
  }
  else{
    antipatharia <- antipatharia %>%     
      terra::project(planning_grid) %>% 
      terra::mask(planning_grid) %>%
      #convert antipatharia habitat suitability to presence/ absence map "by choosing a threshold value of habitat suitability based on the maximum sum of sensitivity and specificity (threshold mss = 0.23)". Text from the original source paper, Yesson et al. 2017
      terra::classify(matrix(c(0, antipatharia_threshold, NA, 
                               antipatharia_threshold, 100, 1), ncol = 3, byrow = TRUE)) %>%
      setNames("antipatharia")
    
    cold_corals <- cold_corals %>% 
      terra::classify(matrix(c(0, 0.5, NA, 
                               0.5, 1.1, 1), ncol = 3, byrow = TRUE)) %>%
      terra::project(planning_grid, method = 'near') %>% 
      terra::mask(planning_grid) %>% 
      setNames("cold_coral")
    
    octocorals <- octocorals %>% 
      terra::classify(matrix(c(0, octocoral_threshold, NA,
                               octocoral_threshold,7, 1), ncol = 3, byrow = TRUE)) %>% 
      terra::project(planning_grid, method = 'near') %>% 
      terra::mask(planning_grid) %>% 
      setNames("octocorals")
    
    corals_stack <- c(antipatharia, cold_corals, octocorals) %>% 
      terra::subset(which(terra::global(., "sum") >1))
    
    return(corals_stack)
  }
  
  gc()
}